# Source code for the Risk Management NLP project
# -*- coding: utf-8 -*-
"""Risk Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp7pQZczgHUCYJ4kPWy7CSRZCiyQiSFr
"""

#Installations
!pip install PyPDF2
!pip install PyMuPDF
!pip install keybert
!pip install rouge
!pip install textacy
!pip install pdfplumber
!pip install rdflib
!pip install bert-score
!pip install autocorrect
!pip install sentence-transformers
!pip install faiss-cpu --no-cache

!python -m spacy download en_core_web_lg

# Commented out IPython magic to ensure Python compatibility.
import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import math
import IPython
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import pdfplumber
import numpy as np
import itertools
import unicodedata
import re
from re import sub
import matplotlib.pyplot as plt
import matplotlib.image as img
import string
from string import punctuation
import time
from pprint import pprint
from sentence_transformers import SentenceTransformer
import faiss
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
from autocorrect import Speller
spell = Speller()
from sentence_transformers import CrossEncoder

from rouge import Rouge

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.probability import FreqDist
from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
from nltk.tree import ParentedTree
from nltk.stem.snowball import SnowballStemmer

# Use English stemmer.
stemmer = SnowballStemmer("english")
from collections import Counter
from tqdm import tqdm

import copy

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

import spacy
nlp = spacy.load("en_core_web_lg")
from spacy.matcher import Matcher
from spacy.matcher import DependencyMatcher
from spacy.tokens import Span
from spacy import displacy

from rdflib.namespace import DC, DCTERMS, DOAP, FOAF, OWL, RDF, RDFS, SKOS, VOID, XMLNS, XSD
from rdflib import URIRef, BNode, Literal, Namespace, Graph
from rdflib.extras import describer

import warnings
warnings.filterwarnings('ignore')

# %matplotlib inline

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

from google.colab import drive
drive.mount('/content/drive')

import PyPDF2
import fitz
import re


# Replace 'your_pdf_file.pdf' with the actual path to your PDF file
pdf_file_path = '/content/drive/MyDrive/PMBOK6-2017_wf.pdf'

# Create a PDF object
pdf_file = open(pdf_file_path, 'rb')
pdf_reader = fitz.open(pdf_file)

import fitz  # PyMuPDF

output_txt_file_path = 'PDF_LINES_NOT_CLEAN.txt'

start_page = 37
end_page = 524

output_txt_file = open(output_txt_file_path, 'w', encoding='utf-8')

# Open the PDF file
pdf_document = fitz.open(pdf_file_path)  # Replace 'your_pdf_file.pdf' with your PDF file path

for page_num in range(start_page - 1, end_page):
    page = pdf_document.load_page(page_num)

    # Extract text from the page
    page_text = page.get_text()

    # Split the page text into lines
    lines = page_text.split('\n')

    # Process each line
    for line in lines:
        print(line)
        output_txt_file.write(line + '\n')

# Close the PDF file
pdf_document.close()

# Close the output text file
output_txt_file.close()

# #Read CSV
# import pandas as pd
# df = pd.read_csv('PDF_LINES_NOT_CLEAN.csv')

file_path = 'PDF_LINES_NOT_CLEAN.txt'

try:
    with open(file_path, 'r',encoding='utf-8') as file:
        # Read the contents of the file
        file_contents = file.read()
        print(file_contents)
except FileNotFoundError:
    print(f"The file '{file_path}' was not found.")

# Replace lines with X page
def replace_lines(input_text):
    i=1
    output_lines = []

    for line in input_text.split('\n'):
        match = re.search(str(i), line)
        if match:
            num = int(match.group())
            if line and num==i and line[0].isdigit():
                rest_of_line = line[len(str(num)):]
                i=i+1
                if num % 2 == 0:
                    # Even number, replace with "NubPage X"
                    output_lines.append(f"NubPage {num}\n{rest_of_line}")
                else:
                    # Odd number, replace with "NubPage X"
                    output_lines.append(f"NubPage {num}\n{rest_of_line}")

        else:
            output_lines.append(line)

    return '\n'.join(output_lines)

lines = replace_lines(file_contents).split('\n')
for line in lines:
    print(line)

#REMOVE UNWANTED CHARCTERS
modified_lines = []
for line in lines:
    modified_line = line.replace("uu", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

# Part 1 - Guide
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace("Part 1 - Guide", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

# u n
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace("u n", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

# "Not For Distribution, Sale or Reproduction."
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace('Not For Distribution, Sale or Reproduction.', "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

# delete empty lines

lines = output_text.split('\n')
non_empty_lines = [line for line in lines if line.strip() != ""]
output_text = '\n'.join(non_empty_lines)

# Remove spaces from the beginning of the every line
lines = output_text.split('\n')
stripped_lines = [line.lstrip() for line in lines]
output_text = '\n'.join(stripped_lines)

#need to clean it from "u m"

lines = output_text.split('\n')
for line in lines:
        print(line, "$")

# #SAVE TO FILE .TXT
# output_txt_file_path = 'PDF_LINES_SEMI_CLEAN.txt'
# output_txt_file = open(output_txt_file_path, 'w',encoding='utf-8')
# for line in lines:
#     output_txt_file.write(line + '\n')

#Split chapters (we have 13 chapters)

import  re
import pandas as pd
Chapters=[]
#Pages=[]
Contents=[]


#initial first chapter
Current_chap="0"
Page="1"
content=""
change_Page=False

#initial chapter 1's
Chapters.append(Current_chap)
#Pages.append(Page)

i=int(Current_chap)+1
Next_chap=str(i)

for line in lines:
    line=line.strip()
    #match = re.search(r"NubPage (\d+)", line)
    #Cheking Chapter
    if line and line==Next_chap :
        Contents.append(content)
        content=""
        change_Page=True
        Current_chap=Next_chap
        i=int(Current_chap)+1
        Next_chap=str(i)
        Chapters.append(Current_chap)
    #elif line and match  :
     #   if match and len(Pages)<i and change_Page:
      #      change_Page=False
       #     page = match.group(1)
        #    page_str = str(int(page) - 1)
            #print(f"Chapter '{Current_chap}'PAGE '{page_str}'")
         #   Pages.append(page_str)
    else:
        content += '\n' + line
print(Current_chap)
Contents.append(content)

# Make sure all lists have the same length by filling any missing data with placeholders
max_length = max(len(Chapters), len(Contents))
Chapters.extend([""] * (max_length - len(Chapters)))
#Pages.extend([""] * (max_length - len(Pages)))
Contents.extend([""] * (max_length - len(Contents)))

# Create the dataframe
df = pd.DataFrame({
    'Chapter': Chapters,
   # 'Page': Pages,
    'Content': Contents,
})

df

lines_chap1=lines

content_chap1=''
for line in lines:
    content_chap1 += '\n' + line
df.at[0, "Content"]=content_chap1

#dropping the first row
df=df.drop(0)
#removing \n
df["Content"] = df["Content"].str.replace(r'^\n', '', 1)

df

import pandas as pd
file_path = 'DF_Chapters_Pages_Content.csv'
# Export the DataFrame to a CSV file
df.to_csv(file_path, index=False)

df_chapters = pd.read_csv(file_path)
df_chapters

# Function to insert the first line from Content into Chapter and remove it from Content
def insert_first_line_to_chapter(row):
    first_line, rest_content = row['Content'].split('\n', 1)
    return str(row['Chapter']) + ' ' + first_line, rest_content

# Apply the function to update Chapter and Content columns
df_chapters[['Chapter', 'Content']] = df_chapters.apply(insert_first_line_to_chapter, axis=1).values.tolist()

df_chapters

df_chap1=df_chapters.head(1)
df_chap1

content_chap1 = df_chap1["Content"].str.split('\n')
content_chap1

#Chapitre 1  TESTING THE CODE
"""
CHAPTER 1 :
    TESTING THE EXTRACTION OF PDF

"""
import  re
content_chap1 = df_chap1["Content"].str.split('\n')


titles_level1=[] #a.x
titles_level2=[] #a.x.x
titles_level3=[] #a.x.x.x
Contents=[]
i=0
content=""
t1=None
t2=None
t3=None

for line_list in content_chap1:
    for i,line in enumerate(line_list):
        match = re.search(r'^1\.\d+(\.\d+)*\s+', line)
        if line and match :
            previous_line = line_list[i -1]
            level=len(match.group(0).split('.'))-1
            #print(level)
            if level==1:
                #print("LEVEL 1")
                titles_level1.append(line)
                titles_level2.append(None)
                titles_level3.append(None)
                t1=line
                #print(f" title'{t1}'")
                t2=None
                t3=None
            if level==2:
                #print("LEVEL 2")
                titles_level1.append(t1)
                titles_level2.append(line)
                titles_level3.append(None)
                t2=line
                t3=None
            if level==3:
            #print("LEVEL 3")
                titles_level1.append(t1)
                titles_level2.append(t2)
                titles_level3.append(line)
                t3=line
            match2 = re.search(r'^1\.\d+(\.\d+)*\s+', previous_line)
            if match2:
                Contents.append(None)
            # If there is content, append it
            if content:
                Contents.append(content.strip())
                content = ""
        else:
        # Append content lines
            content += '\n' + line
# Append any remaining content
    if content:
        Contents.append(content.strip())
    # Make sure all lists have the same length by filling any missing data with placeholders
    max_length = max(len(titles_level1), len(titles_level2), len(titles_level3), len(Contents))
    titles_level1.extend([""] * (max_length - len(titles_level1)))
    titles_level2.extend([""] * (max_length - len(titles_level2)))
    titles_level3.extend([""] * (max_length - len(titles_level3)))
    Contents.extend([""] * (max_length - len(Contents)))

    df_output = pd.DataFrame({
    'TitleL1': titles_level1,
    'TitleL2': titles_level2,
    'TitleL3': titles_level3,
    'Content': Contents,
    })
df_output

# Add new Column for CHAPTER 1 and fix it ;
df_chap1_new=df_output

value_to_fill = df_chapters.iloc[0, 0]
df_chap1_new['Chapter'] = value_to_fill

new_column_name = 'Chapter'
df_chap1_new = df_chap1_new[[new_column_name] + [col for col in df_chap1_new if col != new_column_name]]
df_chap1_new

#ALL THE REST OF THE CHAPTERS FROM 1 TO 13

Final_df = pd.DataFrame({'Chapter': [], 'TitleL1': [], 'TitleL2': [], 'TitleL3': [], 'Content': []})
#Final_df = pd.concat([Final_df,df_chap1_new ], ignore_index=True)

for j in range(1,14):
    df_chap=pd.DataFrame()
    df_chap=df_chapters.iloc[j-1:j]
    content_chap=pd.DataFrame()
    content_chap = df_chap["Content"].str.split('\n')

    titles_level1=[] #a.x
    titles_level2=[] #a.x.x
    titles_level3=[] #a.x.x.x
    t_list=[] #list that contains a.x.x.x parts of all Levels
    Contents=[]
    i=0
    content=""
    t1=None
    t2=None
    t3=None

    for line_list in content_chap:
        for i,line in enumerate(line_list):
            pattern = r'^' + str(j) + r'\.\d+(\.\d+)*\s+'
            match = re.search(pattern, line)
            if line and match and not match.group(0)[:-1] in t_list and "—" not in line:
                #print(t_list)
                previous_line = line_list[i -1]
                level=len(match.group(0).split('.'))-1
                #print(level)

                if len(t_list)==0 and len(Contents)==0 and content:
                    #print(t_list)
                    titles_level1.append(None)
                    titles_level2.append(None)
                    titles_level3.append(None)
                    t1=None
                    t2=None
                    t3=None
                if level==1:
                    #print("LEVEL 1")
                    titles_level1.append(line)
                    titles_level2.append(None)
                    titles_level3.append(None)
                    t1=line
                    t2=None
                    t3=None
                    t1_parts=t1.split(" ")
                    t_list.append(t1_parts[0])
                if level==2:
                    titles_level1.append(t1)
                    titles_level2.append(line)
                    titles_level3.append(None)
                    t2=line
                    t3=None
                    t2_parts=t2.split(" ")
                    t_list.append(t2_parts[0])
                if level==3:
                    titles_level1.append(t1)
                    titles_level2.append(t2)
                    titles_level3.append(line)
                    t3=line
                    t3_parts=t3.split(" ")
                    t_list.append(t3_parts[0])
                match2 = re.search(pattern, previous_line)
                if match2:
                    Contents.append(None)
                # If there is content, append it
                if content :
                    Contents.append(content.strip())
                    content = ""
            else:
            # Append content lines
                content += '\n' + line
    # Append any remaining content
        if content:
            Contents.append(content.strip())
        # Make sure all lists have the same length by filling any missing data with placeholders
        max_length = max(len(titles_level1), len(titles_level2), len(titles_level3), len(Contents))
        titles_level1.extend([""] * (max_length - len(titles_level1)))
        titles_level2.extend([""] * (max_length - len(titles_level2)))
        titles_level3.extend([""] * (max_length - len(titles_level3)))
        Contents.extend([""] * (max_length - len(Contents)))

        df_output = pd.DataFrame({
        'TitleL1': titles_level1,
        'TitleL2': titles_level2,
        'TitleL3': titles_level3,
        'Content': Contents,
        })

    df_chap_new=pd.DataFrame()
    df_chap_new=df_output

    value_to_fill = df_chapters.iloc[j-1, 0]
    df_chap_new['Chapter'] = value_to_fill

    new_column_name = 'Chapter'
    df_chap_new = df_chap_new[[new_column_name] + [col for col in df_chap_new if col != new_column_name]]
    Final_df = pd.concat([Final_df,df_chap_new ], ignore_index=True)
Final_df

Final_df.to_csv("DF_CHAPTERs_SUBTITLEsLv3_CONTENTs_NOT_CLEAN.csv", index=False)

filtered_df = Final_df[Final_df['Chapter'] == '11 PROJECT RISK MANAGEMENT']

filtered_df

import pandas as pd
df2 = pd.DataFrame(columns=['Concept', 'Description'])

for i in range(685,685+len(filtered_df)):
  if(filtered_df['TitleL3'][i]!=None):
    concept=filtered_df['TitleL3'][i]
  else:
    if(filtered_df['TitleL2'][i]!=None):
      concept=filtered_df['TitleL2'][i]
    else:
      if(filtered_df['TitleL1'][i]!=None):
        concept=filtered_df['TitleL1'][i]
      else:
          concept=filtered_df['Chapter'][i]
  print(concept)
  new_row = {'Concept': concept, 'Description': filtered_df['Content'][i]}
  df2 = df2.append(new_row, ignore_index=True)

filtered_df['TitleL2'][685]

df2

df2.to_csv("pmbook_shih.csv", index=False)

for i in range(685,685+len(filtered_df)):
  print(filtered_df["Content"][i])

import nltk
nltk.download('all')


import pandas as pd
from keybert import KeyBERT
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Télécharger les ressources NLTK (si ce n'est pas déjà fait)
nltk.download('punkt')

# Créer un objet KeyBERT avec un modèle BERT pré-entraîné
model = KeyBERT('distilbert-base-nli-mean-tokens')

# Initialiser le lemmatiseur WordNet
lemmatizer = WordNetLemmatizer()

# Fonction pour extraire des mots-clés à partir de la description
def extract_keywords(description_text):
    if not isinstance(description_text, str) or not description_text.strip():
        return []  # Retourne une liste vide pour les entrées non-chaînes ou vides

    print(f"Texte d'origine : {description_text}")

    # Extraire les mots-clés à partir de la description en utilisant KeyBERT
    keywords = model.extract_keywords(description_text, keyphrase_ngram_range=(2, 3), stop_words='english')
    extracted_keywords = [keyword[0] for keyword in keywords]

    # Lemmatisation et fusion des mots-clés
    lemmatized_keywords = []
    unique_keywords = set()
    for keyword in extracted_keywords:
        words = word_tokenize(keyword)  # Tokenize the keyword
        lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
        merged_keyword = " ".join(lemmatized_words)
        # Check for duplicates and keep only unique keywords
        if "updating risk" in merged_keyword:
            merged_keyword = merged_keyword.replace("updating risk", "risk updating")
        if merged_keyword not in unique_keywords:
            lemmatized_keywords.append(merged_keyword)
            unique_keywords.add(merged_keyword)
    print(f"Mots-clés lemmatisés et fusionnés : {lemmatized_keywords}")

    return lemmatized_keywords

# Appliquer la fonction extract_keywords à la colonne 'Description' de votre DataFrame
df2['Keywords'] = df2['Description'].apply(extract_keywords)

# Afficher le DataFrame mis à jour avec les mots-clés extraits, lemmatisés et fusionnés
df2

df2['Description'] = df2['Description'].fillna('')

df2

def convert_to_lowercase(text):
    words = text.split()
    updated_words = [word.lower() if word.isupper() else word for word in words]
    return ' '.join(updated_words)

# Apply the function to the 'Concepts' column
df2['Concept'] = df2['Concept'].apply(convert_to_lowercase)

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("Babelscape/rebel-large")
model = AutoModelForSeq2SeqLM.from_pretrained("Babelscape/rebel-large")

def extract_relations_from_model_output(text):
    relations = []
    relation, subject, relation, object_ = '', '', '', ''
    text = text.strip()
    current = 'x'
    text_replaced = text.replace("<s>", "").replace("<pad>", "").replace("</s>", "")
    for token in text_replaced.split():
        if token == "<triplet>":
            current = 't'
            if relation != '':
                relations.append({
                    'head': subject.strip(),
                    'type': relation.strip(),
                    'tail': object_.strip()
                })
                relation = ''
            subject = ''
        elif token == "<subj>":
            current = 's'
            if relation != '':
                relations.append({
                    'head': subject.strip(),
                    'type': relation.strip(),
                    'tail': object_.strip()
                })
            object_ = ''
        elif token == "<obj>":
            current = 'o'
            relation = ''
        else:
            if current == 't':
                subject += ' ' + token
            elif current == 's':
                object_ += ' ' + token
            elif current == 'o':
                relation += ' ' + token
    if subject != '' and relation != '' and object_ != '':
        relations.append({
            'head': subject.strip(),
            'type': relation.strip(),
            'tail': object_.strip()
        })
    return relations

class KB():
    def __init__(self):
        self.relations = []

    def are_relations_equal(self, r1, r2):
        return all(r1[attr] == r2[attr] for attr in ["head", "type", "tail"])

    def exists_relation(self, r1):
        return any(self.are_relations_equal(r1, r2) for r2 in self.relations)

    def add_relation(self, r):
        if not self.exists_relation(r):
            self.relations.append(r)

    def save(self):
        dict_list = []
        for r in self.relations:
            dict_list.append(r)
        return(dict_list)
        #df = pd.DataFrame(dict_list, columns=['head', 'type', 'tail'])
        #print(dict_list)

def from_small_text_to_kb(text, verbose=False):
    kb = KB()

    # Tokenizer text
    model_inputs = tokenizer(text, max_length=512, padding=True, truncation=True,
                            return_tensors='pt')
    if verbose:
        print(f"Num tokens: {len(model_inputs['input_ids'][0])}")

    # Generate
    gen_kwargs = {
        "max_length": 1000,
        "length_penalty": 0,
        "num_beams": 3,
        "num_return_sequences": 3
    }

    generated_tokens = model.generate(
        **model_inputs,
        **gen_kwargs,
    )

    decoded_preds = tokenizer.batch_decode(generated_tokens, skip_special_tokens=False)

    # create kb
    for sentence_pred in decoded_preds:
        relations = extract_relations_from_model_output(sentence_pred)
        for r in relations:
            kb.add_relation(r)

    return kb

df2['Description'] = df2['Description'].str.encode('utf-8', 'ignore').str.decode('utf-8')

import pandas as pd
relation_list = []

# Étape 3 : Appliquer le code à la colonne 'Descr'
for item in tqdm(df2['Description']):
    if isinstance(item, str):  # Vérifier si l'élément est une chaîne de caractères valide
        try:
            kb = from_small_text_to_kb(item, verbose=False) # Remplacez avec votre fonction
            relation_list.append(kb.save())
        except Exception as e:
            print(f"Erreur : {e} pour l'élément '{item}'") # Afficher les erreurs éventuelles
    else:
        print(f"Attention : élément non valide '{item}'")

# Étape 4 : Vérifiez la longueur de la liste et imprimez-la
print(f"Longueur de la liste : {len(relation_list)}")

# Étape 5 : Si la longueur de la liste est correcte, ajoutez les résultats à une nouvelle colonne du DataFrame
if len(relation_list) == len(df2):
    df2['Relation'] = relation_list
else:
    print("Erreur : La longueur de la liste ne correspond pas à la longueur du DataFrame.")

# Étape 6 : Affichez le DataFrame modifié
print(df2)

dict_list =[]
for item in tqdm(relation_list):
    for dic in item:
        dict_list.append(dic)
triplet = pd.DataFrame(dict_list, columns=['head', 'type', 'tail'])

triplet

unique_triplets = triplet.drop_duplicates()

unique_triplets

tiplet_unique = triplet['head'].unique()

final_triplet_unique = triplet.drop_duplicates(keep='first')

final_triplet_unique = final_triplet_unique.reset_index(drop=True)

final_triplet_unique

text = ''
for item in df2['Description']:
    text += item

text = ''
for item in df2['Description']:
    text += ''.join(item)
example_sent = text
stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(example_sent)
filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)
test_text = ' '.join(filtered_sentence)

import textacy
triple_list = []
for sentence in test_text.split('.'):
    t1 = nlp(sentence)
    triple = textacy.extract.subject_verb_object_triples(t1)
    if triple:
        triple_to_list = list(triple)
        triple_list.append(pd.DataFrame(triple_to_list))
svo=pd.concat(triple_list, axis=0) # this should concat all dfs on top of one another using axis=0
svo.columns=['subject','verb','object'] # change your columns on teh final df

svo

svo = svo.reset_index(drop=True)

final_svo = copy.deepcopy(svo)

for idx,row in final_svo.iterrows():
    for c in final_svo.columns:
        for i in row[c]:
            if isinstance(i, spacy.tokens.span.Span):
                row[c] = i.text
            else:
                row[c] = i

for idx,item in enumerate(final_svo['subject']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['subject'] = item
    else:
        item = item
        final_svo.iloc[idx]['subject'] = item
for idx,item in enumerate(final_svo['verb']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['verb'] = item
    else:
        item = item
        final_svo.iloc[idx]['verb'] = item
for idx,item in enumerate(final_svo['object']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['object'] = item
    else:
        item = item
        final_svo.iloc[idx]['object'] = item

concept_list = []
concept_index = []
for _,row in final_svo.iterrows():
    item = row['subject']
    for i in tiplet_unique:
        if (i in item):
            concept_list.append(item)
            concept_index.append(list(final_svo['subject']).index(item))
svo_unique = dict(zip(concept_index, concept_list))

final_svo_unique = final_svo.drop_duplicates(keep='first')

final_svo_unique

df_final['Concepts'] = data_frame['scope_concepts']
df2['Type_relation'] = ''
df2['Concept_of_type_relation'] = ''

final_triplet_unique = final_triplet_unique.reset_index(drop=True)

final_triplet_unique

for _,row1 in final_triplet_unique.iterrows():
    for _,row2 in df2.iterrows():
        if row1['head'] in row2['Concept']:
            row2['Type_relation'] = row1['type']
            row2['Concept_of_type_relation'] = row1['tail']

df2

df2['reference'] = None
df2['links']= None

import pandas as pd
# Replace 'figre' with 'figure' in the 'Text' column
df2['Description'] = df2['Description'].str.replace('figre', 'figure')

# Print the updated DataFrame
print(df2)

df2['Description'][33]

df2['Description'] = df2['Description'].str.replace('\n', '')
df2['Description'] = df2['Description'].str.replace('theProject', 'the Project')
df2['Description'] = df2['Description'].str.replace('◆', '-')

pattern = r'Figure\d+-\d+'

# Nouveau motif à remplacer
new_pattern = r'Figure \\d+-\\d+'

# Remplacer le motif initial par le nouveau motif
df2['Description'] = df2['Description'].str.replace(pattern, new_pattern)
df2

from numpy.core.multiarray import empty
import re

def extraire_phrases_figure(texte):
    # Utiliser une expression régulière pour trouver les phrases commençant par "Figure"
    phrases_figure = re.findall(r'Figure \d+-\d+', texte)
    return phrases_figure

for i in range(len(df2)):
  empty_list = []
  phrases_figure = extraire_phrases_figure(df2['Description'][i])

# Afficher les phrases extraites
  for phrase in phrases_figure:
      phrase=phrase.replace("Figure ","")
      phrase=phrase.replace(" ","")
      empty_list.append(phrase)
      print(phrase)
  if(phrases_figure!=empty):
    df2['reference'][i]=empty_list

phrases_figure = extraire_phrases_figure(df2['Description'][25])

phrases_figure



!pip install rouge
!pip install textacy
!pip install pdfplumber
!pip install rdflib
!pip install bert-score
!pip install autocorrect
!pip install sentence-transformers
!pip install faiss-cpu --no-cache

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Remplacez 'facebook/bart-large-cnn' par le modèle que vous souhaitez utiliser
model_name = "facebook/bart-large-cnn"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_better_description(description):
    if not pd.isnull(description) and description != "":
        input_text = description
        input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=1024, truncation=True, padding=True)
        output = model.generate(input_ids, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2, top_k=50, top_p=0.95)
        # Extrait la description améliorée du résultat de la génération
        description_amelioree = tokenizer.decode(output[0], skip_special_tokens=True)
        return description_amelioree
    else:
        # Gérez le cas où la description est manquante
        return description

df2['DescriptionAmelioree'] = df2['Description'].apply(generate_better_description)
df2
